#!/usr/bin/env python3

'''
Created on 2018/09/16
@author: heguofeng
'''

import flask

app = flask.Flask(__name__,static_url_path="")

@app.route('/', methods=['POST','GET'])
def index():
    return '<h1>Welcom to IoT World!</h1>'

if __name__ == '__main__':
    app.debug = True
    app.run(host='0.0.0.0', port=5000, threaded=True)
